x-default-isaac-lab-volumes:
  &default-isaac-lab-volumes
    # These volumes follow from this page
    # https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/install_faq.html#save-isaac-sim-configs-on-local-disk

      # These volumes follow from this page
      # https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/install_faq.html#save-isaac-sim-configs-on-local-disk
    - type: volume
      source: isaac-cache-kit
      target: ${ISAAC_SIM_PATH}/kit/cache
    - type: volume
      source: isaac-cache-ov
      target: ${USER_HOME}/.cache/ov
    - type: volume
      source: isaac-cache-pip
      target: ${USER_HOME}/.cache/pip
    - type: volume
      source: isaac-cache-gl
      target: ${USER_HOME}/.cache/nvidia/GLCache
    - type: volume
      source: isaac-cache-compute
      target: ${USER_HOME}/.nv/ComputeCache
    - type: volume
      source: isaac-logs
      target: ${USER_HOME}/.nvidia-omniverse/logs
    - type: volume
      source: isaac-carb-logs
      target: ${ISAAC_SIM_PATH}/kit/logs/Kit/Isaac-Sim
    - type: volume
      source: isaac-data
      target: ${USER_HOME}/.local/share/ov/data
    - type: volume
      source: isaac-docs
      target: ${USER_HOME}/Documents
      # These volumes allow X11 Forwarding
    - type: bind
      source: /tmp/.X11-unix
      target: /tmp/.X11-unix
    - type: bind
      source: ${HOME}/.Xauthority
      target: ${USER_HOME}/.Xauthority
      # This overlay allows changes on the local files to
      # be reflected within the container immediately
    - type: bind
      source: ../
      target: ${RLROVERLAB_PATH}
      # The effect of these volumes is twofold:
      # 1. Prevent root-owned files from flooding the _build and logs dir
      #    on the host machine
      # 2. Preserve the artifacts in persistent volumes for later copying
      #    to the host machine
    - type: volume
      source: orbit-docs
      target: /workspace/orbit/docs/_build
    - type: volume
      source: orbit-logs
      target: /workspace/orbit/logs
    - type: volume
      source: orbit-data
      target: /workspace/orbit/data_storage


x-default-isaac-lab-deploy:
  &default-isaac-lab-deploy
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]


x-default-isaac-lab-enviroment:
  &default-isaac-lab-environment
    ISAAC_SIM_PATH: ${ISAAC_SIM_PATH}
    DISPLAY: ${DISPLAY}
    OMNI_KIT_ALLOW_ROOT: 1

services:
  # This service is used to build the Docker image
  # The docker image is built from the root directory
  #profiles: ["base"]
  rover-lab-base:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ISAAC_SIM_VERSION=${ISAAC_SIM_VERSION}
        - ISAAC_SIM_PATH=${ISAAC_SIM_PATH}
        - USER_HOME=${USER_HOME}
    image: rover-lab-base
    container_name: rover-lab-base
    env_file:
      - .env
    environment: *default-isaac-lab-environment
    volumes: *default-isaac-lab-volumes
    # command: bash -c "${ISAAC_SIM_PATH}/python.sh -m pip install -e ${RLROVERLAB_PATH} && bash"
    network_mode: host
    deploy: *default-isaac-lab-deploy
    # This is the entrypoint for the container
    entrypoint: bash -c "${ISAAC_SIM_PATH}/python.sh -m pip install -e ${RLROVERLAB_PATH} && bash"
    stdin_open: true
    tty: true

  rover-lab-ros2:
    #profiles: ["ros2"]
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile.ros2
      args:
          # ROS2_APT_PACKAGE will default to NONE. This is to
          # avoid a warning message when building only the base profile
          # with the .env.base file
        - ROS2_APT_PACKAGE=${ROS2_APT_PACKAGE:-NONE}
        - USER_HOME=${USER_HOME}
    image: rover-lab-ros2
    container_name: rover-lab-ros2
    environment: *default-isaac-lab-environment
    volumes: *default-isaac-lab-volumes
    network_mode: host
    deploy: *default-isaac-lab-deploy
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true


volumes:
  # isaac-sim
  isaac-cache-kit:
  isaac-cache-ov:
  isaac-cache-pip:
  isaac-cache-gl:
  isaac-cache-compute:
  isaac-logs:
  isaac-carb-logs:
  isaac-data:
  isaac-docs:
  # orbit
  orbit-docs:
  orbit-logs:
  orbit-data: